// <auto-generated />
namespace PRStest.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ActuallyAddedStatusthistime : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ActuallyAddedStatusthistime));
        
        string IMigrationMetadata.Id
        {
            get { return "201802230430475_Actually Added Status this time"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
